CREATE TABLE DEPARTAMENTO 
(ID_DEPARTAMENTO NUMBER NOT NULL,
ID_SUCURSAL NUMBER NOT NULL,
NOMBRE VARCHAR2(25),
DIRECCION VARCHAR2(25));
CREATE TABLE SUCURSAL 
(ID_SUCURSAL NUMBER NOT NULL ,
NOMBRE VARCHAR2(25) CHECK (NOMBRE IN 'MADRID''AMSTERDAM''TENERIFE')UNIQUE,
DIRECCION VARCHAR2(25) UNIQUE);
CREATE TABLE COMERCIAL
(DNI VARCHAR2(9) UNIQUE,
NOMBRE VARCHAR2(20),
APELLIDOS VARCHAR2(20),
fecha_nacimiento DATE,
BONIFICACION VARCHAR2(7),
TITULACION VARCHAR2(25),
ID_DEPARTAMENTO NUMBER NOT NULL,
ID_SUCURSAL NUMBER NOT NULL);
CREATE TABLE PROGRAMADOR 
(DNI VARCHAR2 (9) UNIQUE,
NOMBRE VARCHAR2(25),
APELLIDOS VARCHAR2(25),
fecha_nacimiento DATE,
LENGUAJES VARCHAR2 (255),
PUESTO VARCHAR2 (25),
ID_DEPARTAMENTO NUMBER NOT NULL,
ID_SUCURSAL NUMBER NOT NULL);

CREATE TABLE CLIENTE
(ID_CLIENTE NUMBER NOT NULL,
NOMBRE VARCHAR2(25), 
TELEFONO VARCHAR2(9) UNIQUE,
DIRECCION VARCHAR2(255),
EMAIL VARCHAR2(255) UNIQUE);
CREATE TABLE PROYECTOS
(COD_PROYECTO NUMBER NOT NULL,
NOMBRE VARCHAR2(25),
APELLIDOS VARCHAR2(25),
ID_DEPARTAMENTO NUMBER NOT NULL,
ID_SUCURSAL NUMBER NOT NULL);
CREATE TABLE PROYECTO_CLIENTE
(COD_PROYECTO NUMBER NOT NULL, 
ID_CLIENTE NUMBER NOT NULL);


ALTER TABLE SUCURSAL ADD CONSTRAINT SUCURSAL_pk PRIMARY KEY (ID_SUCURSAL);
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT DEPARTAMENTO_pk PRIMARY KEY (ID_DEPARTAMENTO);
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT DEPARTAMENTO_pk PRIMARY KEY (ID_SUCURSAL) REFERENCES SUCURSAL (ID_SUCURSAL);
ALTER TABLE COMERCIAL ADD CONSTRAINT COMERCIAL_pk PRIMARY KEY (DNI);
ALTER TABLE PROGRAMADOR ADD CONSTRAINT PROGRAMADOR_pk PRIMARY KEY (DNI);
ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_pk PRIMARY KEY (ID_CLIENTE);
ALTER TABLE PROYECTOS ADD CONSTRAINT PROYECTOS_pk PRIMARY KEY (COD_PROYECTO);
ALTER TABLE PROYECTO_CLIENTE ADD CONSTRAINT PROYECTO_CLIENTE_pk PRIMARY KEY (COD_PROYECTO) REFERENCES PROYECTOS (COD_PROYECTO);
ALTER TABLE PROYECTO_CLIENTE ADD CONSTRAINT PROYECTO_CLIENTE_pk PRIMARY KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE);

ALTER TABLE COMERCIAL ADD CONSTRAINT COMERCIAL_FK FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO);
ALTER TABLE COMERCIAL ADD CONSTRAINT COMERCIAL_FK FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL (ID_SUCURSAL);
ALTER TABLE PROGRAMADOR ADD CONSTRAINT PROGRAMADOR_FK FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO);
ALTER TABLE PROGRAMADOR ADD CONSTRAINT PROGRAMADOR_FK FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL (ID_SUCURSAL);
ALTER TABLE PROYECTOS ADD CONSTRAINT PROYECTOS_FK FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO);






